[language-server.harper-ls]
command = "harper-ls"
args = [ "--stdio" ]

[language-server.pylsp.config.pylsp]
plugins.pylsp_mypy.enabled = true
plugins.pylsp_mypy.live_mode = true

[[language]]
name = "go"
language-servers = ["gopls", "harper-ls"]
auto-format = true
formatter = { command = "goimports" }

[[language]]
name = "templ"
auto-format = true
formatter = { command = "templ fmt" }

[[language]]
name = "python"
language-servers = ["pylsp", "ruff-lsp", "harper-ls"]
auto-format = true

[[language]]
name = "markdown"
language-servers = [ "harper-ls" ]
